import React from "react";

export function OperationsModalRouter({
  MCli,
  MPro,
  MPg,
  MCampanaContenido,
  MPiezaContenido,
  MEp,
  MAus,
  MCrew,
  MEvento,
  MActivo,
  MTarea,
  mOpen,
  mData,
  closeM,
  clientes,
  producciones,
  programas,
  piezas,
  oportunidades,
  crew,
  crewOptions,
  listas,
  onSaveCli,
  onSavePro,
  onSavePg,
  onSaveCampana,
  onSavePieza,
  onSaveEp,
  onSaveAus,
  onSaveCrew,
  onSaveEvento,
  onSaveActivo,
  onSaveTarea,
}) {
  return <>
    <MCli
      open={mOpen==="cli"}
      data={mData}
      listas={listas}
      onClose={closeM}
      onSave={onSaveCli}
    />
    <MPro
      open={mOpen==="pro"}
      data={mData}
      clientes={clientes}
      listas={listas}
      onClose={closeM}
      onSave={onSavePro}
    />
    <MPg
      open={mOpen==="pg"}
      data={mData}
      clientes={clientes}
      listas={listas}
      onClose={closeM}
      onSave={onSavePg}
    />
    <MCampanaContenido
      open={mOpen==="contenido"}
      data={mData}
      clientes={clientes}
      listas={listas}
      onClose={closeM}
      onSave={onSaveCampana}
    />
    <MPiezaContenido
      open={mOpen==="pieza"}
      data={mData}
      listas={listas}
      crewOptions={crewOptions}
      onClose={closeM}
      onSave={onSavePieza}
    />
    <MEp
      open={mOpen==="ep"}
      data={mData}
      programas={programas}
      listas={listas}
      onClose={closeM}
      onSave={onSaveEp}
    />
    <MAus
      open={mOpen==="aus"}
      data={mData}
      programas={programas}
      listas={listas}
      onClose={closeM}
      onSave={onSaveAus}
    />
    <MCrew
      open={mOpen==="crew"}
      data={mData}
      listas={listas}
      onClose={closeM}
      onSave={onSaveCrew}
    />
    <MEvento
      open={mOpen==="evento"}
      data={mData}
      producciones={producciones}
      programas={programas}
      piezas={piezas}
      onClose={closeM}
      onSave={onSaveEvento}
    />
    <MActivo
      open={mOpen==="activo"}
      data={mData}
      producciones={producciones}
      listas={listas}
      onClose={closeM}
      onSave={onSaveActivo}
    />
    <MTarea
      open={mOpen==="tarea"}
      data={mData}
      producciones={producciones}
      programas={programas}
      piezas={piezas}
      oportunidades={oportunidades}
      crew={crew}
      listas={listas}
      onClose={closeM}
      onSave={onSaveTarea}
    />
  </>;
}
