import React from "react";
import { CRM_STATUS_OPTIONS, crmCanPassToClient, crmEntityLabel, crmStageMeta } from "../../lib/utils/crm";
import { ModuleHeader } from "../../lib/ui/components";
import { CrmBoard } from "./CrmBoard";
import { CrmDetailModal } from "./CrmDetailModal";
import { CrmStageModal } from "./CrmStageModal";
import { useLabCrmModule } from "../../hooks/useLabCrmModule";

export function CrmModule({
  empresa,
  user,
  crmOpps,
  crmActivities,
  crmStages,
  clientes,
  auspiciadores,
  tareas,
  users,
  openM,
  ntf,
  setClientes,
  setAuspiciadores,
  setCrmOpps,
  setCrmActivities,
  setCrmStages,
  setTareas,
  crmSavingRef,
  TareaCard,
  getRoleConfig,
  uid,
  fmtM,
  fmtD,
  canDo,
}) {
  const {
    isMobile,
    tab,
    setTab,
    q,
    setQ,
    tipo,
    setTipo,
    estado,
    setEstado,
    stageFilter,
    setStageFilter,
    nextActionFilter,
    setNextActionFilter,
    sortKey,
    setSortKey,
    pg,
    setPg,
    selectedIds,
    bulkResponsible,
    setBulkResponsible,
    bulkTipoNegocio,
    setBulkTipoNegocio,
    detail,
    detailActivities,
    detailTasks,
    stagesById,
    activeMobileStageId,
    setMobileStageId,
    mobileStage,
    mobileStageItems,
    activityForm,
    setActivityForm,
    scopedStages,
    scopedOpps,
    tenantUsers,
    nextActionTone,
    sorted,
    paged,
    selectedItems,
    collapsedStages,
    setDetailId,
    setLocalStages,
    setStagesChanged,
    setStagesOpen,
    toggleStageCollapsed,
    updateStage,
    toggleAllVisible,
    toggleSelected,
    updateQuickField,
    exportTarget,
    clearSelection,
    bulkAssignTipoNegocio,
    bulkAssignResponsible,
    bulkDeleteSelected,
    saveStageConfig,
    removeStage,
    stagesOpen,
    localStages,
    passToEntity,
    saveOpp,
    addActivity,
    tasksEnabled,
    canManageCrm,
    canManageTasks,
    PP,
  } = useLabCrmModule({
    empresa,
    user,
    crmOpps,
    crmActivities,
    crmStages,
    clientes,
    auspiciadores,
    tareas,
    users,
    ntf,
    setClientes,
    setAuspiciadores,
    setCrmOpps,
    setCrmActivities,
    setCrmStages,
    setTareas,
    crmSavingRef,
    fmtD,
    canDo,
  });

  return <div>
    <ModuleHeader
      module="CRM"
      title="CRM Comercial"
      description="Gestiona prospectos, etapas, próximas acciones y conversiones a cliente o auspiciador desde un solo pipeline."
    />
    <CrmBoard
      scopedOpps={scopedOpps}
      scopedStages={scopedStages}
      tenantUsers={tenantUsers}
      q={q}
      setQ={setQ}
      tipo={tipo}
      setTipo={setTipo}
      estado={estado}
      setEstado={setEstado}
      stageFilter={stageFilter}
      setStageFilter={setStageFilter}
      nextActionFilter={nextActionFilter}
      setNextActionFilter={setNextActionFilter}
      sortKey={sortKey}
      setSortKey={setSortKey}
      openM={openM}
      setLocalStages={setLocalStages}
      setStagesChanged={setStagesChanged}
      setStagesOpen={setStagesOpen}
      exportTarget={exportTarget}
      selectedItems={selectedItems}
      tab={tab}
      setTab={setTab}
      bulkTipoNegocio={bulkTipoNegocio}
      setBulkTipoNegocio={setBulkTipoNegocio}
      bulkResponsible={bulkResponsible}
      setBulkResponsible={setBulkResponsible}
      bulkAssignTipoNegocio={bulkAssignTipoNegocio}
      bulkAssignResponsible={bulkAssignResponsible}
      bulkDeleteSelected={bulkDeleteSelected}
      clearSelection={clearSelection}
      isMobile={isMobile}
      activeMobileStageId={activeMobileStageId}
      setMobileStageId={setMobileStageId}
      mobileStage={mobileStage}
      mobileStageItems={mobileStageItems}
      fmtM={fmtM}
      setDetailId={setDetailId}
      crmEntityLabel={crmEntityLabel}
      nextActionTone={nextActionTone}
      fmtD={fmtD}
      sorted={sorted}
      collapsedStages={collapsedStages}
      toggleStageCollapsed={toggleStageCollapsed}
      updateStage={updateStage}
      paged={paged}
      selectedIds={selectedIds}
      toggleAllVisible={toggleAllVisible}
      toggleSelected={toggleSelected}
      updateQuickField={updateQuickField}
      CRM_STATUS_OPTIONS={CRM_STATUS_OPTIONS}
      pg={pg}
      setPg={setPg}
      PP={PP}
      crmStageMeta={crmStageMeta}
      canManageCrm={canManageCrm}
    />

    <CrmDetailModal
      detail={detail}
      setDetailId={setDetailId}
      setActivityForm={setActivityForm}
      crmEntityLabel={crmEntityLabel}
      stagesById={stagesById}
      fmtM={fmtM}
      fmtD={fmtD}
      tenantUsers={tenantUsers}
      empresa={empresa}
      crmCanPassToClient={crmCanPassToClient}
      scopedStages={scopedStages}
      passToEntity={passToEntity}
      saveOpp={saveOpp}
      detailActivities={detailActivities}
      activityForm={activityForm}
      addActivity={addActivity}
      ntf={ntf}
      tasksEnabled={tasksEnabled}
      canManageCrm={canManageCrm}
      canManageTasks={canManageTasks}
      openM={openM}
      detailTasks={detailTasks}
      TareaCard={TareaCard}
      scopedOpps={scopedOpps}
      getRoleConfig={getRoleConfig}
    />

    <CrmStageModal
      open={stagesOpen}
      onClose={() => { setStagesOpen(false); setStagesChanged(false); }}
      localStages={localStages}
      scopedStages={scopedStages}
      setLocalStages={setLocalStages}
      setStagesChanged={setStagesChanged}
      removeStage={removeStage}
      saveStageConfig={saveStageConfig}
      createStage={order => ({ id: uid(), name: "Nueva etapa", order, convertToClient: false, closedWon: false, closedLost: false })}
    />
  </div>;
}
